import localFont from "next/font/local";
import { Roboto, Playfair_Display } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["300"],
  variable: "--font-roboto",
});

const playfairDisplay = Playfair_Display({
  subsets: ["latin"],
  variable: ["--font-playfair_display"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${playfairDisplay.variable}`}>
        {children}
      </body>
    </html>
  );
}
